### ISSUE TITLE
margin与padding的使用问题

### ISSUE THREAD

**Issue by BlueMidnightStars** [xiaojilinggui/jianshu#1]
导航栏的首页与小图标。
`<ul class="list-ul">
            <li class="item-ul home"><i class="far fa-compass"></i>
            <a href="#">首页</a></li>
            <li class="item-ul download"><i class="far fa-arrow-alt-circle-down">
            </i><a href="#">下载App</a></li>
            <li class="item-ul search"><a href="#"><input type="text" name="search" value="搜索"></a><i class="fas fa-search"></i></li>
         </ul>`
a标签与i标签的margin与padding相互冲突，
`.fa-arrow-alt-circle-down{
  color: #9e999c;
  margin-right: -15px;
}`
`.item-ul a{
  padding:15px;
  line-height: 58px;
}`
取消其中一个margin或者padding就可以了
至于垂直居中，flex布局中的`align-items:center；`可以解决

**Comment by xiaojilinggui** [comment]
解决
