### ISSUE TITLE
标签使用过多问题以及缺乏行级元素和块级元素的详细了解

### ISSUE THREAD

**Issue by BlueMidnightStars** [xiaojilinggui/jianshu#2]
a标签里包括h2标签虽然没问题，但是没有这个必要去添加h2标签，h2标签在页面里的重要性很大，请谨慎使用，还有就是a标签属于行级标签，h2属于块级标签，行级标签不适合包括块级标签，如果非要使用的话，请将块级标签修改成行内块级标签。
`<a href="#"><h2>我是个标题、我就是个标题还是大的标题</h2></a>`

**Comment by xiaojilinggui** [comment]
已改正
