### ISSUE TITLE
浮动的使用

### ISSUE THREAD

**Issue by BlueMidnightStars** [xiaojilinggui/jianshu#4]
`<div class="summary">
          <div class="text-item">
          <a href="#"><h2>我是个标题、我就是个标题还是大的标题</h2></a>
          <p>探索营销心理学，深入互联网思维，分析赚钱思路，分享创业项目，就在：玩家老高！祝大家早日实现财富自由！‍ </p>
          <p>nomi</p>
          </div>
          <div class="img-item">
          <img src="https://upload-images.jianshu.io/upload_images/4149621-ea695a928574be55.jpg?imageMogr2/auto-orient/strip|imageView2/1/w/300/h/240">
          </div>
        </div>`
这个部分的两个子元素并不需要使用到浮动，请先行了解你使用浮动达到了你想要的效果并不是因为你使用了浮动的原因，更大的一部分是因为浮动将他们变成了行内块级元素。

**Comment by xiaojilinggui** [comment]
已修改
